#!/bin/sh
#
# SPDX-License-Identifier: MIT
#

set -e

UDEVADM="${bindir}/udevadm"
hwdb_bin="$D${sysconfdir}/udev/hwdb.bin"

rm -f "$hwdb_bin"

PSEUDO_UNLOAD=1 ${binprefix}qemuwrapper -L $D $D${UDEVADM} hwdb --update --root $D ||
		PSEUDO_UNLOAD=1 qemuwrapper -L $D $D${UDEVADM} hwdb --update --root $D

if ! test -s "$hwdb_bin"; then
	echo "ERROR: hwdb.bin was not created at $hwdb_bin" >&2
	echo "The hwdb generation command exited successfully but produced no output." >&2
	exit 1
fi
chown root:root "$hwdb_bin"
